// Generated by gencpp from file my_msgs/uwb_type.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_UWB_TYPE_H
#define MY_MSGS_MESSAGE_UWB_TYPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_msgs
{
template <class ContainerAllocator>
struct uwb_type_
{
  typedef uwb_type_<ContainerAllocator> Type;

  uwb_type_()
    : angle(0.0)
    , distance(0.0)  {
    }
  uwb_type_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::my_msgs::uwb_type_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::uwb_type_<ContainerAllocator> const> ConstPtr;

}; // struct uwb_type_

typedef ::my_msgs::uwb_type_<std::allocator<void> > uwb_type;

typedef boost::shared_ptr< ::my_msgs::uwb_type > uwb_typePtr;
typedef boost::shared_ptr< ::my_msgs::uwb_type const> uwb_typeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::uwb_type_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::uwb_type_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_msgs::uwb_type_<ContainerAllocator1> & lhs, const ::my_msgs::uwb_type_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_msgs::uwb_type_<ContainerAllocator1> & lhs, const ::my_msgs::uwb_type_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_msgs::uwb_type_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::uwb_type_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::uwb_type_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::uwb_type_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::uwb_type_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::uwb_type_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::uwb_type_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5a2ee2aaf541b354d2c44aa9ea8522e";
  }

  static const char* value(const ::my_msgs::uwb_type_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5a2ee2aaf541b35ULL;
  static const uint64_t static_value2 = 0x4d2c44aa9ea8522eULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::uwb_type_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/uwb_type";
  }

  static const char* value(const ::my_msgs::uwb_type_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::uwb_type_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#uwb_type.msg\n"
"\n"
"float64 angle\n"
"float64 distance\n"
;
  }

  static const char* value(const ::my_msgs::uwb_type_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::uwb_type_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct uwb_type_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::uwb_type_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::uwb_type_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_UWB_TYPE_H
